# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35c4b195a00b77325b19fd7057f4fed27083ad8cae6bdcf6733d7a7bd417edcf23e7fc755f936982c6e56c130ea13650688cd565d2aa0a7e2f7102d3121d3ea6

test:
  secret_key_base: 0194d158997753a2bf105dfa483c8defc1483763c260f81d01c8212aec9429d798755936c28511e41c25c65f33e777fde11da6fcb3ee6f55305b8f283da97177

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
